IOPLT-139-proessable-module-base
pagopa/io-app-design-system pull request #117
Opened 2023-10-24 09:48 UTC by CrisTofani

## Short description
This PR implements the `PressbaleModuleBase` component refactoring part of the code on `ModuleIDP` and `ModulePaymentNotice`

## List of changes proposed in this pull request
- Creates `PressbaleModuleBase` 
- Refactors `ModuleIDP` and `ModulePaymentNotice`

## How to test
Check the example app on Modules Section

2023-10-24 10:01 UTC, drmarro approved these changes

2023-10-24 10:14 UTC, CrisTofani commented
@dmnplb waiting your approval too for the UI/UX 😄

2023-10-24 12:06 UTC, dmnplb requested changes

2023-10-25 14:17 UTC, CrisTofani commented on example/src/pages/Modules.tsx
> +          important
Added in [1a8d20a](https://github.com/pagopa/io-app-design-system/pull/117/commits/1a8d20aaa85e2e039ca42bb046725be6afedea40)

2023-10-25 14:45 UTC, dmnplb approved these changes

2023-10-27 07:47 UTC, merged