[IOPLT-239] Creates the `Stepper` component
pagopa/io-app-design-system pull request #133
Opened 2023-11-14 12:50 UTC by CrisTofani

## Short description
This PR creates the `Stepper` component

## List of changes proposed in this pull request
- Creates Stepper component
- Include standard example in example App
- Include header integration in example App

## How to test
Check Example app for usage and UI Checking

2023-11-16 10:53 UTC, dmnplb commented on src/components/stepper/Stepper.tsx
> +  padded?: boolean;
```suggestion
```
We need to use this component in a fixed position, so we probably always need to add this property. We can take it for granted.

2023-11-16 10:55 UTC, dmnplb requested changes

2023-11-16 10:55 UTC, dmnplb commented on src/components/stepper/Stepper.tsx
> +  padded?: boolean;
```suggestion
```
We need to use this component in a fixed position, so we probably always need to add this property. We can take it for granted.

2023-11-16 10:55 UTC, dmnplb commented on src/components/stepper/Stepper.tsx
> +  padded = false
```suggestion
```

2023-11-16 10:55 UTC, dmnplb commented on src/components/stepper/Stepper.tsx
> +      }
```suggestion
      style={{ paddingHorizontal: IOVisualCostants.appMarginDefault }}
```

2023-11-17 14:50 UTC, dmnplb approved these changes

2023-11-17 14:58 UTC, merged

2023-11-22 16:58 UTC, thisisjp commented
@CrisTofani @dmnplb looks like the unactive step has a darker gray compared to the design 👀

2023-11-22 17:09 UTC, dmnplb commented
@CrisTofani @thisisjp That's correct, but I missed it completely because the new version (with experimental DS on) has the correct chromatic value. Let's fix it before the next release.