IOPLT-177
pagopa/io-app-design-system pull request #150
Opened 2023-11-27 14:51 UTC by CrisTofani

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-11-28 13:44 UTC, dmnplb requested changes

2023-11-28 13:44 UTC, dmnplb commented on .storybook/main.ts
> +
Can we delete the entire comment block?
```suggestion
```

2023-11-28 13:44 UTC, CrisTofani commented on .storybook/main.ts
> +
Yes, just missed it

2023-11-28 14:32 UTC, dmnplb approved these changes

2023-11-29 09:22 UTC, drmarro approved these changes

2023-11-29 11:00 UTC, merged