[IACROSS-218] Add `Titillium Sans Pro` to all Titillium based typographic styles
pagopa/io-app-design-system pull request #182
Opened 2024-01-29 15:33 UTC by dmnplb

## Short description
This PR applies the new `Titillium Sans Pro` ([official repo here](https://github.com/chialab/titillium_pro)) to all the typographic styles that already use `Titillium Web` in both versions (legacy and new). Therefore, the new typeface will only be visibile when the experimental DS is enabled.

## List of changes proposed in this pull request
- Update all the Titillium-based typographic styles
- Update `ModulePaymentNotice` to use the `LabelSmallAlt` style if experimental DS is enabled
- Update the `Typography` screen in the `example` app

## How to test
1. Run the example app
2. Go to the **Typography** page

2024-01-29 15:43 UTC, CrisTofani requested changes
in order to keep Storybook working properly we need to add the mapping [here](https://github.com/pagopa/io-app-design-system/blob/main/example/assets/css/fonts.css) too

2024-01-29 17:13 UTC, dmnplb commented
> Add path to fonts for Storybook compatibility

Addressed in the commit https://github.com/pagopa/io-app-design-system/pull/182/commits/a7e94c78b2a7ef54b8e11ac1386eca006acee79b

2024-01-30 13:12 UTC, CrisTofani approved these changes

2024-01-30 13:12 UTC, CrisTofani approved these changes
LGTM

2024-01-30 13:52 UTC, merged