IOPLT-137 Introducing storybook
pagopa/io-app-design-system pull request #52
Opened 2023-08-30 14:56 UTC by drmarro

## Short description
Introducing storybook for the DS.
The current implementation provides a basic structure with the typography and ButtonSolid components.

## List of changes proposed in this pull request
- .storybook - Configuration folder for storybook
- /src/stories - The storybook stories with ButtonSolid and Typography components 

## How to test
Run "yarn storybook" to launch storybook on you local env.

2023-08-31 12:52 UTC, dmnplb commented
We should also update the main `README` with the additional info about Storybook

2023-08-31 14:47 UTC, dmnplb requested changes
We should also update the main `README` with the additional info about Storybook

2023-09-01 09:52 UTC, dmnplb commented on example/assets/css/fonts.css
> +} */
```suggestion
```
We don't use `Black` weight in the app, so we could easily delete it.

2023-09-01 09:55 UTC, dmnplb approved these changes

2023-09-01 13:10 UTC, CrisTofani approved these changes

2023-09-01 13:58 UTC, merged